#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=00:15:00
#SBATCH --job-name=InfillSetup

function main() {
    module load anaconda
    module load cuda

    conda activate llmeval

    llm_eval infill_setup
}


main $@
