#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=40:00:00
#SBATCH --job-name=Llama3.2-3B_InfillSolve
#SBATCH --gpus=2
#SBATCH --constraint=h100
#SBATCH --cpus-per-gpu=4

function main() {
    module load anaconda
    echo "loaded anaconda"

    module load cuda
    echo "loaded cuda"

    #conda activate llmeval
    conda activate llmeval
    echo "activated conda environment"

    cd "${HOME}/projects/llmeval"
    echo "changed directory to $(pwd)"

    # setnames
    # llama31_7b_fs
    # llama32_3b_fs
    setname="llama32_3b_fs"

    # models:
    # meta-llama/Llama-3.2-1B-Instruct
    # meta-llama/Llama-3.2-3B-Instruct 
    # meta-llama/Llama-3.3-70B-Instruct
    model="meta-llama/Llama-3.2-3B-Instruct "

    llm_eval infill_solve -m ${model} -p "data/results/infill/${setname}/data.db" -b 10000
}

main $@

