#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=1:00:00
#SBATCH --job-name=TestNestedLoop

function main() {
    module load anaconda
    echo "loaded anaconda"

    module load cuda
    echo "loaded cuda"

    conda activate llmeval
    echo "activated conda environment"

    cd "${HOME}/projects/llmeval"
    echo "changed directory to $(pwd)"

    models=(
        "meta-llama/Llama-3.1-8B-Instruct"
        "meta-llama/Llama-3.2-1B-Instruct"
        "meta-llama/Llama-3.2-3B-Instruct "
        "meta-llama/Llama-3.3-70B-Instruct"
    )
    batchsizes=(
        500
        2500
        5000
        10000
    )
    #"meta-llama/Llama-3.3-70B-Instruct"

    llm_cache="${HOME}/llm_cache"
    echo "------------------"
    for model in ${models[@]}; do
        for batchsize in ${batchsizes[@]}; do
            #./scripts/time_llm -m ${model} -p data/results/infill/20250108-222137/data.db -c data/llm_cache/ -l 10000 -b 10000
            echo "./scripts/time_llm -m ${model} -p data/results/infill/20250108-222137/data.db -c ${llm_cache} -l 10000 -b ${batchsize}"
            echo "rm ${llm_cache}"
        done
    done

}

main $@

